---
- name: Tester si root a un mot de passe défini (connexion via socket sans mot de passe)
  shell: >
    mysql --protocol=socket -uroot --socket=/run/mysqld/mysqld.sock -e "SELECT 1;"
  register: root_pass_check
  ignore_errors: true
  changed_when: false

- name: Configurer le mot de passe root MariaDB (Debian/Ubuntu)
  mysql_user:
    login_unix_socket: /run/mysqld/mysqld.sock
    user: root
    password: "{{ mariadb_root_password }}"
    host: localhost
  become: true
  when: root_pass_check.rc == 0 and ansible_os_family == "Debian"

- name: Configurer le mot de passe root MariaDB (Rocky Linux)
  mysql_user:
    login_unix_socket: /run/mysqld/mysqld.sock
    user: root
    password: "{{ wp_db_root_password }}"
    host: localhost
  when: ansible_os_family == "RedHat"

- name: Supprimer les utilisateurs anonymes
  mysql_user:
    login_user: root
    login_password: "{{ wp_db_root_password }}"
    user: ""
    host_all: true
    state: absent